"""Samples for the Fisher pass, from the bundled self-generated traces.

The traces were generated by the base model itself with the eval's sampling
settings (thinking on). Each Fisher sample is the chat-templated prompt plus
the first ``FISHER_MAX_TOKENS`` tokens of prompt+trace; the loss is taken on the
trace tokens only.
"""

from __future__ import annotations

import hashlib
import json
import random
from pathlib import Path


def load_traces(path, expected_sha256=None):
    path = Path(path)
    if expected_sha256:
        h = hashlib.sha256(path.read_bytes()).hexdigest()
        if h != expected_sha256:
            raise ValueError(f"calibration file hash mismatch: {h}")
    return [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]


def render(tok, row, finished):
    head = tok.apply_chat_template([{"role": "user", "content": row["prompt"]}], tokenize=False,
                                   add_generation_prompt=True, enable_thinking=True)
    full = head + row["trace"] + ("<|im_end|>" if finished else "")
    ids = tok(full, add_special_tokens=False, return_tensors="pt").input_ids
    hl = tok(head, add_special_tokens=False, return_tensors="pt").input_ids.shape[1]
    return ids, hl


def holdout_ids(tok, traces, max_len, max_tokens):
    """The KL evaluation set used by the codec lab (ids of the rows)."""
    fin = [(render(tok, r, True), i) for i, r in enumerate(traces) if not r.get("truncated")]
    fin.sort(key=lambda t: -t[0][0].shape[1])
    used, tok_count, out = set(), 0, []
    for (ids, hl), i in fin:
        if ids.shape[1] <= max_len and tok_count < max_tokens:
            used.add(i)
            out.append((ids, hl))
            tok_count += ids.shape[1] - hl
    return used, out


def fisher_samples(tok, traces, n, max_tokens, exclude, seed=0):
    pool = [r for i, r in enumerate(traces) if i not in exclude and r.get("trace")]
    random.Random(seed).shuffle(pool)
    out = []
    for r in pool:
        if len(out) >= n:
            break
        ids, hl = render(tok, r, not r.get("truncated"))
        if hl + 64 < min(ids.shape[1], max_tokens):
            out.append((ids[:, :max_tokens], hl))
    return out
