"""Build ``calib_data/aime_calib.npz`` from the base-model trace repo (run once).

    python -m compression.build_calib --traces_repo <user>/cs6013-qwen35-4b-base-traces \
        --tokenizer /path/to/Qwen3.5-4B --out compression/calib_data/aime_calib.npz

Not used by compress.py at run time: the output file is committed to the
repository, so compression needs no network and is exactly reproducible.

Source: ``raw/A/aime_20XX.parquet`` (prompt + completion token ids generated by
the base model with the graders' sampling settings) joined with
``derived/A.parquet`` (grader correctness, truncation).

Selection
---------
* GPTQ set: finished + correct traces at full length (ending in <|im_end|>),
  at most ``--per_problem`` per problem; for problems the base model never
  solved, one runaway trace cut to its first ``--runaway_tokens`` tokens.
  Traces are added in a seeded random order until ``--gptq_tokens``.
* Fisher set: ``--fisher_samples`` traces drawn from the remaining samples
  first (then from all), cut to ``--fisher_tokens``; loss is taken on the
  completion part only.

Stored arrays: ``ids`` (int32, all sequences concatenated), ``offsets``,
``lengths``, ``prompt_lens``, ``is_gptq``, ``is_fisher``, plus ``uids`` and
``seeds`` for provenance.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
from pathlib import Path

import numpy as np

YEARS = (2022, 2023, 2024, 2025, 2026)


def load_frames(traces_repo, token=None, local_dir=None):
    import pandas as pd

    def get(path):
        if local_dir:
            return str(Path(local_dir) / path)
        from huggingface_hub import hf_hub_download
        return hf_hub_download(traces_repo, path, repo_type="dataset", token=token)

    raw = pd.concat([pd.read_parquet(get(f"raw/A/aime_{y}.parquet")) for y in YEARS],
                    ignore_index=True)
    der = pd.read_parquet(get("derived/A.parquet"))
    der = der[der.source.str.startswith("aime_")]
    df = raw.merge(der[["uid", "sample_idx", "correct_grader", "truncated"]],
                   on=["uid", "sample_idx"], how="inner")
    return df


def build(df, im_end_id, gptq_tokens, per_problem, runaway_tokens, fisher_samples,
          fisher_tokens, seed=0):
    rng = random.Random(seed)
    recs = []
    for r in df.itertuples(index=False):
        p = list(r.prompt_token_ids)
        c = list(r.completion_token_ids)
        if r.finish_reason == "stop" and (not c or c[-1] != im_end_id):
            c = c + [im_end_id]
        recs.append({"uid": r.uid, "seed": int(r.seed), "p": p, "c": c,
                     "correct": bool(r.correct_grader), "trunc": bool(r.truncated)})
    by_uid = {}
    for i, r in enumerate(recs):
        by_uid.setdefault(r["uid"], []).append(i)

    cand = []
    for uid, idx in by_uid.items():
        good = [i for i in idx if recs[i]["correct"] and not recs[i]["trunc"]]
        rng.shuffle(good)
        if good:
            cand += [(i, None) for i in good[:per_problem]]
        else:
            run = [i for i in idx if recs[i]["trunc"]] or idx
            cand.append((rng.choice(run), runaway_tokens))
    rng.shuffle(cand)

    seqs, used, tok = [], set(), 0
    for i, cap in cand:
        if tok >= gptq_tokens:
            break
        ids = recs[i]["p"] + recs[i]["c"]
        if cap is not None:
            ids = ids[:cap]
        seqs.append({"ids": ids, "plen": len(recs[i]["p"]), "gptq": True, "fisher": False,
                     "uid": recs[i]["uid"], "seed": recs[i]["seed"]})
        used.add(i)
        tok += len(ids)

    rest = [i for i in range(len(recs)) if i not in used]
    rng.shuffle(rest)
    pool = rest + [i for i in range(len(recs)) if i in used]
    nf = 0
    for i in pool:
        if nf >= fisher_samples:
            break
        ids = (recs[i]["p"] + recs[i]["c"])[:fisher_tokens]
        if len(ids) - len(recs[i]["p"]) < 64:
            continue
        seqs.append({"ids": ids, "plen": len(recs[i]["p"]), "gptq": False, "fisher": True,
                     "uid": recs[i]["uid"], "seed": recs[i]["seed"]})
        nf += 1
    return seqs


def save(seqs, out):
    lengths = np.array([len(s["ids"]) for s in seqs], dtype=np.int64)
    offsets = np.concatenate([[0], np.cumsum(lengths)[:-1]]).astype(np.int64)
    ids = np.concatenate([np.asarray(s["ids"], dtype=np.int32) for s in seqs])
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        out, ids=ids, offsets=offsets, lengths=lengths,
        prompt_lens=np.array([s["plen"] for s in seqs], dtype=np.int64),
        is_gptq=np.array([s["gptq"] for s in seqs]), is_fisher=np.array([s["fisher"] for s in seqs]),
        uids=np.array([s["uid"] for s in seqs]), seeds=np.array([s["seed"] for s in seqs]))
    return hashlib.sha256(out.read_bytes()).hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--traces_repo", required=True)
    ap.add_argument("--tokenizer", required=True)
    ap.add_argument("--out", default=str(Path(__file__).parent / "calib_data" / "aime_calib.npz"))
    ap.add_argument("--token", default=None)
    ap.add_argument("--local_dir", default=None, help="read raw/ and derived/ from a local copy")
    ap.add_argument("--gptq_tokens", type=int, default=2_000_000)
    ap.add_argument("--per_problem", type=int, default=2)
    ap.add_argument("--runaway_tokens", type=int, default=8192)
    ap.add_argument("--fisher_samples", type=int, default=256)
    ap.add_argument("--fisher_tokens", type=int, default=4096)
    a = ap.parse_args()

    from transformers import AutoTokenizer
    im_end = AutoTokenizer.from_pretrained(a.tokenizer).convert_tokens_to_ids("<|im_end|>")
    df = load_frames(a.traces_repo, a.token, a.local_dir)
    seqs = build(df, im_end, a.gptq_tokens, a.per_problem, a.runaway_tokens,
                 a.fisher_samples, a.fisher_tokens)
    sha = save(seqs, a.out)
    g = [s for s in seqs if s["gptq"]]
    f = [s for s in seqs if s["fisher"]]
    stats = {
        "source_samples": len(df), "source_problems": int(df.uid.nunique()),
        "gptq_sequences": len(g), "gptq_tokens": int(sum(len(s["ids"]) for s in g)),
        "gptq_problems": len({s["uid"] for s in g}),
        "gptq_max_len": int(max(len(s["ids"]) for s in g)),
        "fisher_sequences": len(f), "fisher_tokens": int(sum(len(s["ids"]) for s in f)),
        "sha256": sha,
    }
    print(json.dumps(stats, indent=2))
    Path(a.out).with_suffix(".json").write_text(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()
