"""Calibration data for GPTQ and for the energy pre-pass -- policy E.

Source: ``calib_data/traces_all.jsonl``, 240 reasoning traces generated by the
base model itself with the eval's sampling settings (AIME 24/25/26, MATH-500,
MMLU-Pro maths). Each row holds the user ``prompt`` and the generated
``trace`` (thinking text, ``</think>``, answer), plus a ``truncated`` flag for
traces that hit the 32K generation limit.

Policy E
--------
* **Finished traces** are used at full length, with ``<|im_end|>`` appended.
  Their late positions and their exit (``</think>`` -> answer -> end of turn) are
  exactly the behaviour a compressed model loses when its parse rate drops.
* **Runaway traces** keep only their first ``RUNAWAY_MAX_TOKENS`` tokens,
  prompt included. Their heads are ordinary reasoning; their tails are loops,
  which we do not want to dominate the Hessians.
* **One conversation per sample, no padding, no packing.** Samples have
  variable length and are run with batch size 1, so no attention mask exists,
  every position id is the real one, and the Gated DeltaNet recurrent state is
  never carried across two unrelated conversations.

The text is rebuilt exactly as the eval serves it: the chat template with
``enable_thinking=True`` and the generation prompt (which ends in ``<think>``),
followed by the trace.
"""

from __future__ import annotations

import hashlib
import json
import random
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

import torch

END_OF_TURN = "<|im_end|>"


@dataclass
class CalibStats:
    n_samples: int
    n_finished: int
    n_runaway: int
    n_tokens: int
    n_tokens_runaway: int
    min_len: int
    max_len: int
    mean_len: float
    n_tokens_beyond_8k: int
    n_exits: int  # samples that contain </think> followed by the end-of-turn

    def format(self) -> str:
        return (
            "\n" + "=" * 68 + "\nCalibration set (policy E)\n" + "=" * 68 + "\n"
            f"  samples                 : {self.n_samples} "
            f"({self.n_finished} finished, {self.n_runaway} runaway)\n"
            f"  tokens                  : {self.n_tokens:,} "
            f"({self.n_tokens_runaway:,} from runaway heads)\n"
            f"  length min/mean/max     : {self.min_len:,} / {self.mean_len:,.0f} / {self.max_len:,}\n"
            f"  tokens at positions >8K : {self.n_tokens_beyond_8k:,}\n"
            f"  samples with an exit    : {self.n_exits}\n" + "=" * 68
        )


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def load_traces(path: Path, expected_sha256: Optional[str]) -> List[dict]:
    path = Path(path).expanduser()
    if not path.exists():
        raise FileNotFoundError(f"Calibration traces not found at {path}")
    if expected_sha256:
        got = sha256_file(path)
        if got != expected_sha256:
            raise ValueError(
                f"Calibration file hash mismatch.\n  expected {expected_sha256}\n"
                f"  got      {got}\nThe traces file was modified or truncated."
            )
    rows = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def render_prompt(tokenizer, prompt: str) -> str:
    """Chat-template the user turn exactly as the eval does (thinking on)."""
    try:
        text = tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=True,
        )
    except TypeError:  # templates that do not accept enable_thinking
        text = tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=False,
            add_generation_prompt=True,
        )
    return text


def build_calibration(
    tokenizer,
    calib_file,
    expected_sha256: Optional[str] = None,
    runaway_max_tokens: int = 8192,
    max_seq: Optional[int] = None,
    limit_samples: Optional[int] = None,
    seed: int = 0,
    verbose: bool = True,
):
    """Return ``(samples, stats)``; each sample is a ``[1, L_i]`` LongTensor."""
    rows = load_traces(Path(calib_file), expected_sha256)
    rows = [r for r in rows if r.get("trace") and not r.get("failed")]

    if limit_samples is not None:
        # Keep a mix of finished and runaway traces even in smoke mode.
        rng = random.Random(seed)
        fin = [r for r in rows if not r.get("truncated")]
        run = [r for r in rows if r.get("truncated")]
        rng.shuffle(fin)
        rng.shuffle(run)
        n_run = min(len(run), max(1, limit_samples // 4)) if run else 0
        rows = fin[: limit_samples - n_run] + run[:n_run]

    samples: List[torch.Tensor] = []
    lens, n_fin, n_run, tok_run, n_exit = [], 0, 0, 0, 0
    think_close = "</think>"
    shown = False

    for row in rows:
        head = render_prompt(tokenizer, row["prompt"])
        if not shown and verbose:
            print("[calib] rendered generation prompt ends with:", repr(head[-40:]))
            if not head.rstrip().endswith("<think>"):
                print("[calib] WARNING: generation prompt does not end in <think>; "
                      "the template may not have thinking mode on.")
            shown = True

        truncated = bool(row.get("truncated"))
        text = head + row["trace"]
        if not truncated:
            text = text + END_OF_TURN

        ids = tokenizer(text, add_special_tokens=False, return_tensors="pt").input_ids[0]

        if truncated:
            ids = ids[:runaway_max_tokens]
            n_run += 1
            tok_run += ids.numel()
        else:
            n_fin += 1
            if think_close in row["trace"]:
                n_exit += 1
        if max_seq is not None:
            ids = ids[:max_seq]

        samples.append(ids.unsqueeze(0).contiguous())
        lens.append(ids.numel())

    stats = CalibStats(
        n_samples=len(samples),
        n_finished=n_fin,
        n_runaway=n_run,
        n_tokens=int(sum(lens)),
        n_tokens_runaway=int(tok_run),
        min_len=int(min(lens)),
        max_len=int(max(lens)),
        mean_len=float(sum(lens) / len(lens)),
        n_tokens_beyond_8k=int(sum(max(0, n - 8192) for n in lens)),
        n_exits=n_exit,
    )
    return samples, stats


def select_for_energy(samples: List[torch.Tensor], max_tokens: int, seed: int = 0):
    """A seeded random subset of samples totalling about ``max_tokens`` tokens."""
    order = list(range(len(samples)))
    random.Random(seed + 1).shuffle(order)
    picked, total = [], 0
    for i in order:
        if total >= max_tokens:
            break
        picked.append(samples[i])
        total += samples[i].shape[1]
    return picked, total
